//decleration: let x;
//assign/init: x = 100;
//combination: let x = 100;

//console.log(typeof iAge)
//console.log(`You are ${iAge} years old`);
//console.log(`You are ` + iAge + ` years old`);

/*let iNumber = 1

while (iNumber <= 8) {
    iNumber += 1
}*/

//console.log(9 ** 4)
// exponants is **

// mod: 30 % 2 = 0 (remainder is the mod awnser)

// delphi: JS
// inc(): var++
// dec(): var--

//document.getElementById(`h1`).textContent = iNumber



